# Generated by Django 2.1.12 on 2020-03-31 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noww', '0002_auto_20200331_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_url',
        ),
    ]
