# Generated by Django 2.1.12 on 2020-03-31 16:25

from django.db import migrations
import nowwapi.utils


class Migration(migrations.Migration):

    dependencies = [
        ('noww', '0003_remove_user_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=nowwapi.utils.GoogleBucketUrlField(blank=True, null=True),
        ),
    ]
