TASK_STATUSES_PROCESS = [
    'PENDING',
    'AWAITING_PAYMENT',
    'AWAITING_FULFILLMENT',
    'AWAITING_SHIPMENT',
    'AWAITING_PICKUP',
    'SHIPPED',
    'REFUNDED'
]

TASK_STATUSES_FINAL = [
    'CREATED',
    'IN_PROGRESS',
    'COMPLETED',
    'REJECTED'
]

TASK_STATUSES_CANCELLED = [
    'CANCELLEDBYWORKER',
    'CANCELLEDBYCUSTOMER'

]

TASK_STATUSES = TASK_STATUSES_PROCESS + TASK_STATUSES_FINAL + TASK_STATUSES_CANCELLED
